# Copyright © 2023 Radiology Partners, Inc. - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

name: build-test-win
on:
  workflow_dispatch:

  push:
    branches:
      - "!*"
      - "dev"
    tags:
      - "v*"
  pull_request:
    branches: [ dev, main ]
     
jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3

    - name: Test environment
      run: |
        echo "github.ref"
        echo ${{ github.ref }} 
        echo ${{ !startsWith(github.ref, 'refs/tags/v') }} 
        echo "github.actor"
        echo ${{ github.actor }} 
        echo ${{ !startsWith(github.actor, 'dependabot') }}
        echo "end"

